# Archivo yamalin
# Respetar identación de los elementos
name: CI/CD Pipeline con Matrix Build
# Bloque on indica cuando se ejecuta el workflow
on:
    push:
        branches:
            - main
    # Fusión de ramas de diferentes usuarios (reconciliación)
    pull_request:
        branches:
            - main
# Bloques de trabajos realizados
jobs:
    # Nombre del job sin espacios ni símbolos especiales
    # Job de compilación
    compilacion-pruebas:
        # En que tipo de máquina se ejecuta
        runs-on: ${{ matrix.os }} # Nueva forma de parametrizar manejo de máquinas
        # Bloque para definir los datos de la matriz
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                java: [25, 26]
        # Pasos a ejecutar
        steps:
            - name: clonando el repositorio
              uses: actions/checkout@v6.1.0 # Buscar lista de actions en catálogo de github
            - name: Configurar JDK ${{ matrix.java }}
              uses: actions/setup-java@v6.0.1
              with: # Bloque de atributos adicionales para el action
                distribution: 'temurin'
                java-version: '${{ matrix.java }}'
            # Paso para cachear dependencias
            - name: Cache de paquetes maven
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                # Ruta de la carpeta de configuración para cachear dependencias
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Herramientas disponibles por github
            - name: compilar el proyecto
              # run: mvn spring-boot:run & # evitar salida en consola con &
              run: mvn clean package -DskipTests
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
                  NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
            - name: Ejecutar proyecto
              shell: bash # Indicar que se trabaje con bash para compatibilidad en windows
              run: |
                java -jar target/demo-0.0.1-SNAPSHOT.jar &
                echo $! > springboot.pid
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
                  NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
            - name: Esperar y probar un endpoint
              shell: bash
              run: | # dirigir salida del comando anterior
                sleep 20
                curl http://localhost:8080/actuator/health
            # Este bloque no se puede ejecutar por que se borra el archivo ejecutado
            #- name: Ejecutando test con maven
            #  shell: bash
            #  run: mvn clean verify
            #  env:
            #      DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
            #      NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
            - name: Detener aplicación
              shell: bash
              run: kill -9 $(cat springboot.pid) # leer de archivo y sustituir con parentesis ()
            # Bloque para ejecución manual del análisis del código con sonarcloud
            - name: Ejecutando análisis de código
              shell: bash
              # Ejecución de análisis conectandose con sonarcloud
              # Buscar proyectKey en URL del proyecto
              run: mvn sonar:sonar \
                   -Dsonar.projectKey=omarsangalaura_20260916 \
                   -Dsonar.host.url=https://sonarcloud.io \
                   -Dsonar.organization=omarsangalaura
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  SONAR_HOST_URL: https://sonarcloud.io
    # Bloque para otro job de despliegue
    deploy:
        # Bloque para controlar la ejecución del job si otro job fue exitoso
        needs: compilacion-pruebas
        runs-on: ubuntu-latest
        # Condicional para restringir ejecución al estar en rama main con un evento push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        steps:
            - name: Checkout
              uses: actions/checkout@v6.1.0
            - name: Configurar JDK 26
              uses: actions/setup-java@v6.0.1
              with:
                distribution: 'temurin'
                java-version: '26'
            - name: Cache de paquetes maven
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                # Ruta de la carpeta de configuración con dependencias cacheadas
                # ubuntu por el nombre del so
                key: ubuntu-maven-${{ hashFiles('**/pom.xml') }}
                # Orden para recuperar los archivos cacheadas para ubuntu
                restore-key: | 
                  ubuntu-maven-
            - name: Compilar el proyecto
              run: mvn clean package -DskipTests
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
                  NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
#            - name: Desplegar el servidor remoto
#              uses: appleboy/ssh-action@v0.1.6
#              with:
#                host: ${{ secrets.REMOTE_HOST }}
#                username: ${{ secrets.USERNAME }}
#                key: ${{ secrets.KEY }}
#                script: |
#                    cd /ruta/al/proyecto
#                    git pull origin main
#                    mvn clean package -DskipTests
#                    nohup java -jar target/demo-0.0.1-SNAPSHOT.jar &
