# Archivo yamalin
# Respetar identación de los elementos
name: CI/CD Pipeline con Matrix Build
# Bloque on indica cuando se ejecuta el workflow
on:
    push:
        branches:
            - main
    # Fusión de ramas de diferentes usuarios (reconciliación)
    pull_request:
        branches:
            - main
# Bloques de trabajos realizados
jobs:
    # Nombre del job sin espacios ni símbolos especiales
    # Job de compilación
    compilacion:
        # En que tipo de máquina se ejecuta
        runs-on: ${{ matrix.os }} # Nueva forma de parametrizar manejo de máquinas
        # Bloque para definir los datos de la matriz
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                java: [25, 26]
        # Pasos a ejecutar
        steps:
            - name: clonando el repositorio
              uses: actions/checkout@v6.1.0 # Buscar lista de actions en catálogo de github
            - name: Configurar JDK ${{ matrix.java }}
              uses: actions/setup-java@v6.0.1
              with: # Bloque de atributos adicionales para el action
                distribution: 'temurin'
                java-version: '${{ matrix.java }}'
            # Paso para cachear dependencias
            - name: Cache de paquetes maven
              uses: actions/cache@v4
              with:
                path: ~/.m2/repository
                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }} # Herramientas disponibles por github
            - name: compilar el proyecto
              # run: mvn spring-boot:run & # evitar salida en consola con &
              run: mvn clean package -DskipTests
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
                  NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
            - name: Ejecutar proyecto
              run: |
                java -jar target/demo-0.0.1-SNAPSHOT.jar &
                echo $! > springboot.pid
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
                  NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
            - name: Esperar y probar un endpoint
              run: | # dirigir salida del comando anterior
                sleep 20
                curl http://localhost:8080/actuator/health
            - name: Detener aplicación
              run: kill -9 $(cat springboot.pid) # leer de archivo y sustituir con parentesis ()