# Archivo yamalin
# Respetar identación de los elementos
name: Mi primer CI/CD Pipeline
# Bloque on indica cuando se ejecuta el workflow
on:
    push:
        branches:
            - main
    # Fusión de ramas de diferentes usuarios (reconciliación)
    pull_request:
        branches:
            - main
# Bloques de trabajos realizados
jobs:
    # Nombre del job sin espacios ni símbolos especiales
    # Job de compilación
    compilacion:
        # En que tipo de máquina se ejecuta
        runs-on: ubuntu-latest # Buscar tipos de máquinas desde catálogo de github
        # Pasos a ejecutar
        steps:
            - name: clonando el repositorio
              uses: actions/checkout@v6.1.0 # Buscar lista de actions en catálogo de github
            - name: Configurar JDK 21
              uses: actions/setup-java@v6.0.1
              with: # Bloque de atributos adicionales para el action
                distribution: 'temurin'
                java-version: '21'
            - name: compilar el proyecto
              # run: mvn spring-boot:run & # evitar salida en consola con &
              run: mvn clean package -DskipTests
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
                  NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
            - name: Ejecutar proyecto
              run: |
                java -jar target/demo-0.0.1-SNAPSHOT.jar &
                echo $! > springboot.pid
              env:
                  DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
                  NOMBRE_USR: ${{ secrets.NOMBRE_USR }}
            - name: Esperar y probar un endpoint
              run: | # dirigir salida del comando anterior
                sleep 20
                curl http://localhost:8080/actuator/health
            - name: Detener aplicación
              run: kill -9 $(cat springboot.pid)